plugins:
  - jemoji              # GitHub-style emoji

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: default

# Optional nav list
nav_pages:
  - title: "Cross Index"
    url: /toc.html
